Created Prodsec Blog Part
side-projects-overkill/vue-security-page pull request #3
Opened 2024-07-11 13:13 UTC by atharvkulkarni2002

2024-07-12 08:19 UTC, hybridx requested changes

2024-07-12 08:19 UTC, hybridx commented on vue-security-page/index.html
> +    />
Import this in main styles

2024-07-12 08:20 UTC, hybridx commented
rest LGTM

2024-07-12 09:01 UTC, atharvkulkarni2002 commented on vue-security-page/index.html
> +    />
removed from index.html and added to main.css

2024-07-13 14:47 UTC, yashoswalyo approved these changes
LGTM

2024-07-13 14:51 UTC, yashoswalyo approved these changes
LGTM

2024-07-13 14:53 UTC, yashoswalyo commented
Can you move `.github` folder out of `vue-security-page` in root

2024-07-15 05:38 UTC, rohit-bharmal commented on vue-security-page/src/components/blog/ProdsecBlog.vue
> +        <div
Can we use pf-card here for all of this cards ?

2024-07-15 05:52 UTC, rohit-bharmal commented on vue-security-page/src/components/blog/ProdsecBlog.vue
> +.security-overview li {
add one line space after one css property completed.

2024-07-15 06:53 UTC, hybridx commented
Please use eslint

2024-07-15 06:54 UTC, hybridx commented
https://dev.to/ankitt8/setting-up-eslint-airbnb-configuration-prettier-and-husky-pre-commit-hooks-in-cra-5dbo

2024-07-15 14:35 UTC, hybridx approved these changes

2024-07-15 14:35 UTC, merged